<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1>Login</h1>
<?php if ($alert = $this->getAlert()): ?>
    <h3><?php echo $alert ?></h3>
<?php endif; ?>
<form action="login" method="post">
<p>Username: <input type="text" name="username"/></p>
<p>Password: <input type="password" name="password"/></p>
<button type="submit">Login</button>
</form>
</body>
</html>